# Generated by Django 6.0 on 2025-12-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Orthopedics, Cardiology, General Surgery', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('total_capacity', models.IntegerField(help_text='Maximum number of patients the hospital can admit.')),
                ('specialties', models.ManyToManyField(help_text='Select all specialties offered by this hospital.', related_name='hospitals', to='hospitals.specialty')),
            ],
        ),
    ]
