# Generated by Django 6.0 on 2025-12-07 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueSpecialtyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_term', models.CharField(help_text="Specific patient issue (e.g., 'Broken leg', 'Flu', 'Aortic event')", max_length=100, unique=True)),
                ('primary_specialty', models.ForeignKey(help_text='The standardized specialty this issue belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='mapped_issues', to='hospitals.specialty')),
            ],
            options={
                'verbose_name': 'Issue to Specialty Map',
                'verbose_name_plural': 'Issue to Specialty Maps',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('health_issue', models.CharField(help_text="The specific issue reported by the patient (e.g., 'Fractured arm').", max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('IN', 'Admitted (In-Patient)'), ('OUT', 'Discharged (Out-Patient)')], default='PENDING', help_text='Current status of the patient.', max_length=10)),
                ('check_in_date', models.DateTimeField(blank=True, help_text='Automatically set when the patient is assigned/admitted.', null=True)),
                ('assigned_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to='hospitals.hospital')),
            ],
        ),
    ]
